# Generated by Django 3.0.2 on 2020-01-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='hire_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
