# Generated by Django 3.0.2 on 2020-01-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20200104_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default='teacher', max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='teacher_id',
            field=models.CharField(default='1234', max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(default='new', max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('LR', 'Lecturer'), ('AP', 'Assistant Professor'), ('PF', 'Professor')], default='LR', max_length=200),
        ),
    ]
