# Generated by Django 3.0.2 on 2020-01-04 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0004_auto_20200104_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('lession_time', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.Staff')),
            ],
        ),
    ]
