# Generated by Django 3.0.2 on 2020-01-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasub', '0001_initial'),
        ('staff', '0004_auto_20200104_1113'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='clasub',
            field=models.ManyToManyField(to='clasub.Clasub'),
        ),
        migrations.AddField(
            model_name='student',
            name='staff',
            field=models.ManyToManyField(to='staff.Staff'),
        ),
    ]
