# Generated by Django 3.0.2 on 2020-01-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200104_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='staff',
        ),
    ]
